#' Deposit data on Zenodo
#'
#' @param timestamp timestamp to be uploaded
#' @param token Zenodo token to upload the deposit, The default is to take it
#'   from the environment variable `ZENODO_PAT`. The internal helper function
#'   from `zen4R` is used. You can set it using `Sys.setenv(ZENODO_PAT = "YOUR_PAT_HERE")`.
#' @param data_package_dir directory in which the datapackages to be deposited can be found
#' @param metadata_bib bibliographic metadata as generated by the function
#'   \code{zen_metadata()}
#' @param metadata_pre_processed file name of the zip file with the metadata for the pre-processed data
#' @param metadata_extracted file name of the zip file with the metadata for the extracted data
#' @param publish if \code{TRUE} publish the packages immediately - should
#'   normally be \code{FALSE}
#' @param sandbox if `TRUE` (default) upload to the Zenodo sandbox for testing,
#'   if `FALSE` upload to the "real" Zenodo
#'
#' @return list with all info concerning the deposits
#'
#' @md
#'
#' @importFrom utils zip
#' @importFrom zen4R ZenodoManager ZenodoRecord
#'
#' @export
#'
leef_deposit <- function(
    timestamp,
    token = zen4R:::zenodo_pat(),
    data_package_dir,
    metadata_extracted,
    metadata_pre_processed,
    metadata_bib,
    publish = FALSE,
    sandbox = TRUE
){

  # For Safety during testing -----------------------------------------------


  message("Publishing is disabled until finalising of the Function!")
  message("Sandbox is always used until finalising of the Function!")
  publish <- FALSE
  sandbox <- TRUE


  # Preparations ------------------------------------------------------------


  if (sandbox) {
    url <- "https://sandbox.zenodo.org/api"
  } else {
    url <- "https://zenodo.org/api"
  }
  ##

  deposits <- list(
    pre_processed = list(
      stage = "pre_processed",
      data = file.path(
        data_package_dir,
        paste0("data_pre_processed_", timestamp, ".zip")
      ),
      metadata = metadata_pre_processed
    ),
    extracted = list(
      stage = "extracted",
      data = file.path(
        data_package_dir,
        paste0("data_extracted_", timestamp, ".zip")
      ),
      metadata = metadata_extracted
    )
  )



  lapply(
    deposits,
    function(x){
      if (!file.exists(x$data)) {
        stop("Data file for stage ", x$stage, " does not exist!")
      }
      if (!file.exists(x$metadata)) {
        stop("Metadata file for stage ", x$stage, " does not exist!")
      }
    }
  )


  # Connect to Zenodo -------------------------------------------------------


  zenodo <- zen4R::ZenodoManager$new(
    url = url,
    token = token,
    logger = "INFO"
  )


  # Create individual records ------


  deposits <- lapply(
    deposits,
    function(x){


      # Adapt metadata following leef standards ----------------------------------------


      metadata_bib$title <-  paste0(title, " ", x["stage"], " data from ", as.Date(timestamp, "%Y%m%d"))
      metadata_bib$keywords <- c(
        metadata_bib$keywords,
        x["stage"],
        paste0("timestamp_", timestamp),
        as.Date(timestamp, "%Y%m%d")
      )


      # Create and populate records -------------------------------------------------


      rec <- add_metadata_bib(metadata_bib)


      # Upload records ----------------------------------------------------------


      x$rec <- zenodo$depositRecord(rec)
      x$doi <- x$rec$metadata$prereserve_doi$doi


      # Upload data files ----------------------------------------------------------


      zenodo$uploadFile(x$metadata, x$rec)
      zenodo$uploadFile(x$data, x$rec)


      # End ---------------------------------------------------------------------


      return(x)
    }
  )


  # Add related identifiers -------------------------------------------------


  deposits[["pre_processed"]]$rec$addRelatedIdentifier(
    identifier = deposits[["extracted"]]$doi,
    relation = "isDerivedFrom",
    resource_type = "dataset"
  )
  deposits[["pre_processed"]]$rec <- zenodo$depositRecord(deposits[["pre_processed"]]$rec)

  deposits[["extracted"]]$rec$addRelatedIdentifier(
    identifier = deposits[["pre_processed"]]$doi,
    relation = "isSourceOf",
    resource_type = "dataset"
  )
  deposits[["extracted"]]$rec <- zenodo$depositRecord(deposits[["extracted"]]$rec)


  # Publish deposits

  if (publish) {
    recs <- lapply(
      deposits,
      function(x){
        zenodo$publishRecord(x$rec$id)
      }
    )
  }

  return(deposits)
}


