#' Deposit data on Zenodo
#'
#' @param timestamp timestamp to be uploaded
#' @param token Zenodo token to upload the deposit
#' @param data_dir directory in which the data to be deposited can be found
#' @param metadata_bib bibliographic metadata as generated by the function \code{zen_metadata()}
#' @param publish if \code{TRUE} publish the packages immediately - should normally be \code{FALSE}
#' @param sandbox if `TRUE` (default) upload to the Zenodo sandbox for testing, if `FALSE` upload to the "real" Zenodo
#'
#' @return list with all info concerning the deposits
#'
#' @md
#'
#' @importFrom utils zip
#' @importFrom zen4R ZenodoManager ZenodoRecord
#'
#' @export
#'
zen_deposit <- function(
    timestamp,

    token = NULL,


    data_dir = "./tmp",

    metadata_bib = leef_metadata_bib(),

    publish = FALSE,
    sandbox = TRUE
){

  # For Safety during testing -----------------------------------------------


  message("Publishing is disabled until finalising of the Function!")
  message("Sandbox is always used until finalising of the Function!")
  publish <- FALSE
  sandbox <- TRUE


  # Preparations ------------------------------------------------------------


  if (sandbox) {
    url <- "https://sandbox.zenodo.org/api"
  } else {
    url <- "https://zenodo.org/api"
  }
  ##

  deposits <- list(
    pre_processed = list(
      stage = "pre_processed",
      data = file.path(
        data_dir,
        paste0("data_pre_processed_", timestamp, ".zip")
      ),
      metadata = file.path(
        data_dir,
        paste0("metadata_pre_processed.zip")
      )
    ),
    extracted = list(
      stage = "extracted",
      data = file.path(
        data_dir,
        paste0("data_extracted_", timestamp, ".zip")
      ),
      metadata = file.path(
        data_dir,
        paste0("metadata_extracted.zip")
      )
    )
  )

  lapply(
    deposits,
    function(x){
      if (!file.exists(x$data)) {
        stop("Data file for stage ", x$stage, " does not exist!")
      }
      if (!file.exists(x$metadata)) {
        stop("Metadata file for stage ", x$stage, " does not exist!")
      }
    }
  )


  # Connect to Zenodo -------------------------------------------------------


  zenodo <- zen4R::ZenodoManager$new(
    url = url,
    token = token,
    logger = "INFO"
  )


  # Create individual records ------


  deposits <- lapply(
    deposits,
    function(x){


      # Create and populate records -------------------------------------------------


      rec <- zen4R::ZenodoRecord$new()

      rec$setUploadType(metadata_bib$upload_type)
      title = paste0("LEEF Experiment ", x["stage"], " data from ", as.Date(timestamp, "%Y%m%d"))
      rec$setTitle(title)
      #   paste0(
      #     "LEEF Experiment ", x["stage"], " data from ", as.Date(timestamp, "%Y%m%d")
      #   )
      # )
      lapply(
        metadata_bib$authors,
        function(aut){
          rec$addCreator(
            firstname = aut$firstname,
            lastname = aut$lastname,
            affiliation = aut$affiliation,
            orcid = aut$orcid
          )
        }
      )
      rec$setDescription(metadata_bib$description)
      rec$setVersion(metadata_bib$version)
      rec$setLanguage(metadata_bib$language)
      keywords <- c(
        metadata_bib$keywords,
        x["stage"],
        paste0("timestamp_", timestamp),
        as.Date(timestamp, "%Y%m%d")
      )
      rec$setKeywords(metadata_bib$keywords)
      rec$setLicense(metadata_bib$license)
      rec$setAccessRight(metadata_bib$access_right)
      # rec$setGrants("654359") # eLTER
      # rec$setGrants("871126") # eLTER-PPP
      # rec$setGrants("871128") # eLTER-Plus
      lapply(
        metadata_bib$contributors,
        function(con){
          rec$addContributor(
            firstname = con$firstname,
            lastname = con$lastname,
            type = con$type,
            affiliation = con$affiliation,
            orcid = con$orcid
          )
        }
      )

      x$rec <-  rec


      # Upload records ----------------------------------------------------------


      x$rec <- zenodo$depositRecord(x$rec)
      x$doi <- x$rec$metadata$prereserve_doi$doi


      # Upload data files ----------------------------------------------------------


      zenodo$uploadFile(x$metadata, x$rec)
      zenodo$uploadFile(x$data, x$rec)


      # End ---------------------------------------------------------------------


      return(x)
    }
  )


  # Add related identifiers -------------------------------------------------


  deposits[["pre_processed"]]$rec$addRelatedIdentifier(
    identifier = deposits[["extracted"]]$doi,
    relation = "isDerivedFrom",
    resource_type = "dataset"
  )
  deposits[["pre_processed"]]$rec <- zenodo$depositRecord(deposits[["pre_processed"]]$rec)

  deposits[["extracted"]]$rec$addRelatedIdentifier(
    identifier = deposits[["pre_processed"]]$doi,
    relation = "isSourceOf",
    resource_type = "dataset"
  )
  deposits[["extracted"]]$rec <- zenodo$depositRecord(deposits[["extracted"]]$rec)


  # Publish deposits

  if (publish) {
    recs <- lapply(
      deposits,
      function(x){
        zenodo$publishRecord(x$rec$id)
      }
    )
  }

  return(deposits)
}


